version: '3'
services: 
  nginx:
    image: nginx
    ports: 
      - '8000:80'
    depends_on: 
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php:
    build: .
    volumes:
      - .:/var/www/html
    depends_on: 
      - db
  db:
    image: mariadb
    ports:
      - '3310:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
volumes:
  db_data: