version: '3'
services: 
  nginx:
    image: nginx
    ports: 
      - '8000:80'
    depends_on: 
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  
  php:
    image: php:fpm
    volumes:
      - .:/var/www/html
